# Generated by Django 3.1.2 on 2020-11-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digits',
            name='result',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
